### ISSUE TITLE
Storyboard height/width bug

### ISSUE THREAD

**Issue by ttoavina** [flitsoft/flutter_storyboard#8]
Different size behaviour between local and pipeline

**Comment by tolotrasamuel** [comment]
This seems to be fine on flit ride, tested with 

Got the exact same value on Pipeline and Local for this code

```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:get_it/get_it.dart';
import 'package:ride_app/common/my_circular_progress_indicator.dart';
import 'package:ride_app/common/utils.dart';
import 'package:ride_app/model/version.dart';
import 'package:ride_app/rider/pages/splash/spash_controller.dart';
import 'package:ride_app/services/message_ui_factory.dart';

class SplashPage extends StatefulWidget {
  SplashPage({Key? key}) : super(key: key);
  @override
  SplashPageState createState() => SplashPageState();
}

class SplashPageState extends State<SplashPage> {
  final MessageUiFactory messageUiFactory =
      GetIt.instance.get<MessageUiFactory>();
  late SplashController controller;

  NavigatorState get navigator => Navigator.of(context);
  Locale get locale => Localizations.localeOf(context);

  @override
  void initState() {
    super.initState();
    controller = SplashController();
    print('$logTrace Welcome');

    SchedulerBinding.instance!.addPostFrameCallback((Duration _) {
      controller.attach(this);
      controller.initState();

      final width = MediaQuery.of(context).size.width;
      final height = MediaQuery.of(context).size.height;
      final dpr = MediaQuery.of(context).devicePixelRatio;
      final textScale = MediaQuery.of(context).textScaleFactor;
      final vi = MediaQuery.of(context).viewInsets;
      final vip = MediaQuery.of(context).viewPadding;
      final font = DefaultTextStyle.of(context).style.fontFamily;
      print(
          "width is $width and height is $height and dpi is $dpr txtScale is $textScale vi is $vi vip is $vip font is $font");
    });
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: FutureBuilder(
          future: controller.versionService.getInitialized(),
          initialData: false,
          builder: (_, __) {
            return StreamBuilder(
                stream: controller.versionService.stream,
                builder: (ctx, AsyncSnapshot<Version?> snapshot) {
                  if (snapshot.hasData) {
                    if (snapshot.data!.status != VersionStatus.ok) {
                      return Center(
                        child: Material(
                          child: Text(
                            '''${messageUiFactory.get(MyStrings.ERROR_YOUR_VERSION_IS)} ${describeEnum(snapshot.data!.status)}, updgrade !''',
                            style: TextStyle(color: Colors.red),
                          ),
                        ),
                      );
                    } else {
                      return Center(
                        child: MyCircularProgressIndicator(),
                      );
                    }
                  }
                  return Center(
                    child: MyCircularProgressIndicator(),
                  );
                });
          }),
    );
  }
}

```
#  width is 360 and height is 740 and dpi is 4 txtScale is 1 vi is EdgeInsets.zero vip is EdgeInsets(0.0, 24.0, 0.0, 0.0) font is monospace

**Comment by tolotrasamuel** [comment]
Also, as of today, there is no visual discrepancy in Flit Ride and local (mac book chrome Checking for updates
Version 102.0.5005.61 (Official Build) (x86_64)) 

Flit ride hash 

FR-727  Fix Codemagic for Flit Ride new Repo (#10) heriniaina-rak* 30/05/2022, 09:51 472e29b2

**Comment by tolotrasamuel** [comment]
Difference may lies in devicePixelRatio, 1 in ci and 2 locally.

I could not find a flag to increase this https://github.com/GabrielBB/xvfb-action/blob/master/index.js that uses

https://www.x.org/archive/X11R7.6/doc/man/man1/Xvfb.1.xhtml


#Remote
#] JAVASCRIPT {"availHeight":2160,"availLeft":0,"availTop":0,"availWidth":3840,"colorDepth":24,"height":2160,"isExtended":false,"onchange":null,"orientation":{},"pixelDepth":24,"**devicePixelRatio":1,"**width":3840}

#Local
#"availHeight":1095,"availLeft":0,"availTop":25,"availWidth":1792,"colorDepth":30,"height":1120,"isExtended":false,"onchange":null,"orientation":{},"pixelDepth":30,"**devicePixelRatio":2,**"width":1792}'


This will allow adding chrome flags to flutter , so maybe this https://stackoverflow.com/a/47082369/6727914 can be implemented with --force-device-scale-factor=2


https://github.com/flutter/flutter/issues/65575

**Comment by tolotrasamuel** [comment]
#        width is 480 and height is 986.6666666666666 and dpi is 4 txtScale is 1 vi is EdgeInsets.zero vip is EdgeInsets.zero font is monospace

#   {ctxDevicePixelRatio: 4, windowDevicePixelRation: 1, ctxSize: Size(360.0, 740.0), uiSize: Size(1905.0, 2067.0), ctxTextScale: 1, uiCtxTextScale: 1, uiPadding: Instance of 'WindowPadding', ctxPadding: EdgeInsets(0.0, 24.0, 0.0, 0.0), ctxViewPadding: EdgeInsets(0.0, 24.0, 0.0, 0.0), ctxViewInsets: EdgeInsets.zero, uiViewPadding: Instance of 'WindowPadding', uiViewInsets: Instance of 'WindowPadding'}

#local
# {ctxDevicePixelRatio: 4, windowDevicePixelRation: 2, ctxSize: Size(360.0, 740.0), uiSize: Size(2442.0, 1854.0), ctxTextScale: 1, uiCtxTextScale: 1, uiPadding: Instance of 'WindowPadding', ctxPadding: EdgeInsets(0.0, 24.0, 0.0, 0.0), ctxViewPadding: EdgeInsets(0.0, 24.0, 0.0, 0.0), ctxViewInsets: EdgeInsets.zero, uiViewPadding: Instance of 'WindowPadding', uiViewInsets: Instance of 'WindowPadding'}



#Flit`
#Remote
#  {ctxDevicePixelRatio: 1, windowDevicePixelRation: 1, ctxSize: Size(1905.0, 2067.0), uiSize: Size(1905.0, 2067.0), ctxTextScale: 1, uiCtxTextScale: 1, uiPadding: Instance of 'WindowPadding', ctxPadding: EdgeInsets.zero, ctxViewPadding: EdgeInsets.zero, ctxViewInsets: EdgeInsets.zero, uiViewPadding: Instance of 'WindowPadding', uiViewInsets: Instance of 'WindowPadding'}

#Local
#  {ctxDevicePixelRatio: 4, windowDevicePixelRation: 2, ctxSize: Size(360.0, 740.0), uiSize: Size(2152.0, 1854.0), ctxTextScale: 1, uiCtxTextScale: 1, uiPadding: Instance of 'WindowPadding', ctxPadding: EdgeInsets(0.0, 24.0, 0.0, 0.0), ctxViewPadding: EdgeInsets(0.0, 24.0, 0.0, 0.0), ctxViewInsets: EdgeInsets.zero, uiViewPadding: Instance of 'WindowPadding', uiViewInsets: Instance of 'WindowPadding'}

**Comment by tolotrasamuel** [comment]
#  width is 360 and height is 740 and dpi is 4 txtScale is 1 vi is EdgeInsets.zero vip is EdgeInsets(0.0, 24.0, 0.0, 0.0) font is monospace


#Remote with xvfb
#] JAVASCRIPT {"availHeight":2160,"availLeft":0,"availTop":0,"availWidth":3840,"colorDepth":24,"height":2160,"isExtended":false,"onchange":null,"orientation":{},"pixelDepth":24,"devicePixelRatio":1,"width":3840}

#remote with xvfb and chrome headless
#  {"availHeight":1800,"availLeft":0,"availTop":0,"availWidth":2400,"colorDepth":24,"height":1800,"isExtended":false,"onchange":null,"orientation":{},"pixelDepth":24,"devicePixelRatio":1,"width":2400}
#Local
#"availHeight":1095,"availLeft":0,"availTop":25,"availWidth":1792,"colorDepth":30,"height":1120,"isExtended":false,"onchange":null,"orientation":{},"pixelDepth":30,"devicePixelRatio":2,"width":1792}'



#remote with force-pixel-ratio=2
#  {ctxDevicePixelRatio: 4, windowDevicePixelRation: 2, ctxSize: Size(360.0, 740.0), uiSize: Size(4800.0, 3600.0), ctxTextScale: 1, uiCtxTextScale: 1, uiPadding: Instance of 'WindowPadding', ctxPadding: EdgeInsets(0.0, 24.0, 0.0, 0.0), ctxViewPadding: EdgeInsets(0.0, 24.0, 0.0, 0.0), ctxViewInsets: EdgeInsets.zero, uiViewPadding: Instance of 'WindowPadding', uiViewInsets: Instance of 'WindowPadding'}

**Comment by tolotrasamuel** [comment]
# Use xvfb without git action wrapper
https://stackoverflow.com/questions/70401128/is-there-a-way-to-set-an-specific-display-at-chromium-launch-options

 - name: "Run storyboard cli"
      id: storyboard
      shell: "bash"
      run: |
        echo "Storyboard flow is: "
        echo ${{ inputs.storyboard-flow}}
        sudo apt-get install -y xvfb
        which xdpyinfo
        which Xvfb
        export DISPLAY=:99
        /usr/bin/Xvfb :99 -screen 0 2000x2000x24 -dpi 200 &
        sleep 5
        xvfb-run --auto-servernum dart run --define=STORYBOARD_FLOW=${{ inputs.storyboard-flow }} runner.dart

**Comment by tolotrasamuel** [comment]
# Solution modify chrome to accept flag for flutter
https://askubuntu.com/a/697724

  steps:
    - name: "modify chrome"
      id: modifyChrome
      shell: "bash"
      run: |
        google-chrome --version
        which google-chrome
        cat /usr/bin/google-chrome
        echo "checking usr bin chrome"
        echo "If you cat  cat /usr/bin/google-chrome, you will see that when running in a wrapper, it looks for this file instead of opt one, not sure why but this is the solution"
        sudo ln -s /opt/google/chrome/chrome /usr/bin/chrome
        sudo cp /usr/bin/google-chrome /usr/bin/google-chrome-bak
        echo "checking original chrome"
        ls /usr/bin/google-chrome-bak
        echo /usr/bin/google-chrome-bak --force-device-scale-factor=2 \"\$\@\" > my-google-chrome
        cat my-google-chrome
        chmod +x my-google-chrome
        echo "checking original chrome"
        ls /usr/bin/google-chrome-bak
        sudo cp my-google-chrome /usr/bin/google-chrome
        which google-chrome
        cat /usr/bin/google-chrome
        echo "CAT USR BIN!!!!"
        echo "Chrome help!!!!"
        google-chrome --version

**Comment by tolotrasamuel** [comment]
https://peter.sh/experiments/chromium-command-line-switches/#force-device-scale-factor

Chrome flag list

**Comment by tolotrasamuel** [comment]
Mety
============

xvfb
-screen 0 4920x2160x24
(24 seems to be slower than 30)

Chrome
scale force to 2
no window size

https://github.com/Tolotra-mg/tolotra_mg/runs/6724462525?check_suite_focus=true
14min

============

no xvfb

Chrome
scale force to 1
echo /usr/bin/google-chrome-bak \"\$\@\" --window-size=1280,960 > my-google-chrome

https://github.com/Tolotra-mg/tolotra_mg/pull/41/checks
8:50 min

=======

no xvfb

Chrome
scale force to 2
echo /usr/bin/google-chrome-bak --force-device-scale-factor=2 \"\$\@\" --window-size=1280,960 > my-google-chrome

https://github.com/Tolotra-mg/tolotra_mg/runs/6727350347?check_suite_focus=true
18:50 min

===

**Comment by tolotrasamuel** [comment]
quick branch without all overflow https://github.com/Tolotra-mg/tolotra_mg/tree/fix/android-studio-hanging
